### PR TITLE
Adding option to restrict serach by country

### PR DESCRIPTION
**Pull request by dmuneras**
Adding option to restrict search by country (for example).

### CODE REVIEW

**Comment by rsander23** [comment]
Hey,
is it possible to resolve the conflicts and merge this feature?

Best Rob

**Comment by dmuneras** [comment]
Hi @rsander23 

Sure, let me do it today.

Regards,
Daniel.

**Comment by rsander23** [comment]
wonderful! 👍

**Comment by esbanarango** [comment]
@rsander23 This feature is merged and is now available on `v0.0.11`.

**Pull request merged**
