### PR TITLE
Add workaround for bug where clicking auto-suggestion does not update…

### PR DESCRIPTION
**Pull request by tshuck**
… value

See the bound url param below:
change value

I dunno if this is the proper way to fix or not, but it does work -- very open to suggestions.

### CODE REVIEW

**Comment by dmuneras** [comment]
Hi @tshuck,

Thanks for help us to improve this addon, let me check if there is a better solution and let you know. 

Best regards,
Daniel.

**Comment by esbanarango** [comment]
@tshuck Could you resolve the conflicts on this branch pls.

**Comment by dmuneras** [comment]
@tshuck  could check if this solve your problem?  https://github.com/dmuneras/ember-place-autocomplete/pull/17

**Comment by jstoup111** [comment]
@dmuneras this is still an issue https://github.com/dmuneras/ember-place-autocomplete/issues/26

**Comment by dmuneras** [comment]
Hi @tshuck 

We released a new version, it seems to be fixed in this version, could you confirm that to be able to close this issue?

Regards,
Daniel

**Pull request closed without merging**
