### PR TITLE
Fix fields to array issue

### PR DESCRIPTION
**Pull request by sinankeskin**
There is a extra this here.

### CODE REVIEW

**Comment by dmuneras** [comment]
Thanks @sinankeskin!

**Comment by dmuneras** [comment]
Tomorrow I am going to merge the version upgrades and release a new version.

**Comment by sinankeskin** [comment]
Awesome. Thank you.

**Comment by sinankeskin** [comment]
Hi @dmuneras 

It has been long time but I believe you forgot to create a new release.

**Pull request merged**
