### PR TITLE
Add option to prevent the form to be submitted when hitting ENTER

### PR DESCRIPTION
**Pull request by lionelrudaz**
Goal: add an option to avoid the form to be submitted when hitting
ENTER on the places autocompleter

New property preventSubmit added. Set to false by default to not change
the default behavior.

Add a new keyDown event handler to prevent the ENTER key to submit the
form if the option is enabled and we have a location.

Let me know if you need more information.

### CODE REVIEW

**Comment by esbanarango** [comment]
@lionelrudaz Thank you! Could you add tests to this new functionality and update the readme with its proper explanation pls.

**Comment by lionelrudaz** [comment]
@esbanarango sure I'd love to help. I commit an update of the README.

I have troubles with tests. Tests don't complete locally. Check the screenshot below:

screen1

Then, since I'm a bit of a newbie when it comes to testing, what do you think I should add? A Unit test? An Acceptance test?

Thanks for your advice

**Comment by dmuneras** [comment]
@lionelrudaz thanks a lot for your contribution. It has been almost a year since this is open, I think this is a useful option to add. It would be nice if you can rebase against the master branch  so I can merge it. 

Best regards,
Daniel.

**Comment by lionelrudaz** [comment]
@dmuneras I'm sorry, but I don't have much time at the moment... :( Can you do it without me?

**Comment by dmuneras** [comment]
Hey @lionelrudaz and @esbanarango, I am going to do an small/quick rebase/rewrite of this, due to the ember upgrade that I did couple of days ago. Thanks a lot @lionelrudaz for doing this.

**Comment by esbanarango** [comment]
🙏👌

**Comment by dmuneras** [comment]
@lionelrudaz  I am going to close this PR in favor of this one: https://github.com/dmuneras/ember-place-autocomplete/pull/66 

I forked from your branch, but I had to create another branch to be able to merge. 

is that ok?

Best regards,
Daniel.

**Pull request closed without merging**
